version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/aws-2048-pipeline
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runs: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runs: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runs: ec2-user
